from pydantic import BaseModel
from fastapi import FastAPI, Depends, HTTPException
from sqlalchemy.orm import Session
import models
from database import engine, SessionLocal

# 1. The Architect: Create tables of they don't exist
models.Base.metadata.create_all(bind=engine)

app = FastAPI()

# 2. Dependency: Get the Database Session
def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
    

@app.get("/")

async def root():

    return {"message": "Hello World"}

class UserPayLoad(BaseModel):
    name:str
    experience_years:int

@app.post("/submit")
def create_user(user: UserPayLoad, db: Session = Depends(get_db)):
    # 1. Calculate the Business Logic
    determined_status = "Intern"
    if user.experience_years >= 1:
        determined_status = "Pro"

    # 2. Create the Database Model
    # We map the data from the API (user) to the Database Table (models.User)
    db_user = models.User(
        name=user.name, 
        experience_years=user.experience_years, 
        status=determined_status
    )

    # 3. The Transaction
    db.add(db_user)      # Add to the "shopping cart"
    db.commit()          # Pay and checkout (save to DB)
    db.refresh(db_user)  # Reload the object to get the new ID generated by the DB

    return db_user