from pydantic import BaseModel
from fastapi import FastAPI, Depends, HTTPException
from sqlalchemy.orm import Session
import models
from database import engine, SessionLocal

# 1. The Architect: Create tables of they don't exist
models.Base.metadata.create_all(bind=engine)

app = FastAPI()

# 2. Dependency: Get the Database Session
def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
    

@app.get("/")

async def root():

    return {"message": "Hello World"}

class UserPayLoad(BaseModel):
    name:str
    experience_years:int

##### FASTAPI ENDPOINT 1
@app.post("/submit")
def create_user(user: UserPayLoad, db: Session = Depends(get_db)):
    # 1. Calculate the Business Logic
    determined_status = "Intern"
    if user.experience_years >= 1:
        determined_status = "Pro"

    # 2. Create the Database Model
    # We map the data from the API (user) to the Database Table (models.User)
    db_user = models.User(
        name=user.name, 
        experience_years=user.experience_years, 
        status=determined_status
    )

    # 3. The Transaction
    db.add(db_user)      # Add to the "shopping cart"
    db.commit()          # Pay and checkout (save to DB)
    db.refresh(db_user)  # Reload the object to get the new ID generated by the DB

    return db_user

##### FASTAPI ENDPOINT 2a

@app.get("/users")
def get_users(db: Session = Depends(get_db)):
    users = db.query(models.User).all()
    return users

##### FASTAPI ENDPOINT 2b

@app.get("/users/{user_id}")
def get_user(user_id: int, db: Session = Depends(get_db)):
    # .filter() is like the WHERE clause in SQL
    user = db.query(models.User).filter(models.User.id == user_id).first()
    
    if not user:
        raise HTTPException(status_code=404, detail="User not found")
    
    return user


##### FASTAPI ENDPOINT 3

@app.put("/users/{user_id}")
def update_user(user_id: int, updated_user: UserPayLoad, db: Session = Depends(get_db)):
    # 1. Find the user
    db_user = db.query(models.User).filter(models.User.id == user_id).first()
    
    if not db_user:
        raise HTTPException(status_code=404, detail="User not found")
    
    # 2. Update the fields
    db_user.name = updated_user.name
    db_user.experience_years = updated_user.experience_years
    
    # 3. RE-CALCULATE Logic (Crucial Step)
    if db_user.experience_years >= 1:
        db_user.status = "Pro"
    else:
        db_user.status = "Intern"
    
    # 4. Save changes
    db.commit()
    db.refresh(db_user)
    return db_user

##### FASTAPI ENDPOINT 4

@app.delete("/users/{user_id}")
def delete_user(user_id: int, db: Session = Depends(get_db)):
    # 1. Find the user
    db_user = db.query(models.User).filter(models.User.id == user_id).first()
    
    if not db_user:
        raise HTTPException(status_code=404, detail="User not found")
    
    # 2. Delete
    db.delete(db_user)
    db.commit()
    
    return {"message": f"User {user_id} deleted successfully"}